In [4]:
import pandas as pd
from shapely.geometry  import shape, Point
from geopy.geocoders import Nominatim
import json
import os
import glob

In [2]:
with open('../../geojsons/Boundaries - Community Areas (current).geojson') as f:
    commarea = json.load(f)

In [ ]:
x = '../'

In [6]:
data_path = '../311/'
cur_dir = os.getcwd()

os.chdir(data_path)
files = glob.glob("*.json")
os.chdir(cur_dir)

In [ ]:
geolocator = Nominatim(user_agent="test_tk")

In [8]:
bigdf = pd.DataFrame()

for file in files:
    bigdf = pd.concat([bigdf,pd.read_json((data_path+file), lines=True)],axis=0)

In [12]:
bigdf.drop(['location.latitude', 
            'location.longitude', 
            'location.human_address', 
            'city', 
            'state', 
            'created_department',
            'sanitation_division_days',
            'street_address',
            'street_number',
            'street_direction',
            'street_name',
            'street_type',
            'electricity_grid',
            'police_sector',
            'x_coordinate',
            'y_coordinate',
            'ward',
            'electrical_district',
            'last_modified_date',
            'parent_sr_number',
            'police_beat'], 
            axis=1, inplace=True)

In [17]:
bigdf.to_csv('./re/311_merged.csv', index=False)

In [16]:
bigdf[bigdf['sr_short_code'] == 'SKA']

,sr_number,sr_type,sr_short_code,owner_department,status,origin,created_date,closed_date,zip_code,duplicate,legacy_record,community_area,police_district,precinct,created_hour,created_day_of_week,created_month,latitude,longitude
2,SR19-00000028,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Web,2019-01-01T00:35:57.000,2019-04-15T22:01:28.000,None,False,False,NaN,NaN,NaN,0,3,1,NaN,NaN
3,SR19-00000029,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Web,2019-01-01T00:36:03.000,2019-04-15T22:01:28.000,None,False,False,NaN,NaN,NaN,0,3,1,NaN,NaN
89,SR19-00001882,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Phone Call,2019-01-01T14:55:56.000,2019-04-15T22:01:28.000,60651,False,False,25.0,25.0,5.0,14,3,1,41.905539,-87.763745
102,SR19-00002055,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Phone Call,2019-01-01T15:52:18.000,2019-04-15T22:01:28.000,60629,False,False,66.0,8.0,33.0,15,3,1,41.759488,-87.685263
125,SR19-00002377,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Phone Call,2019-01-01T17:42:09.000,2019-04-15T22:01:28.000,60639,False,False,25.0,25.0,10.0,17,3,1,41.913004,-87.751722
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499915,SR23-00516788,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Alderman's Office,2023-04-05T10:39:13.000,2023-04-11T09:23:35.000,NaN,False,False,22.0,14.0,19.0,10,4,4,41.923575,-87.700189
499937,SR23-00516833,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Mobile Device,2023-04-05T10:47:34.000,2023-04-29T04:04:33.000,NaN,False,False,43.0,3.0,30.0,10,4,4,41.770908,-87.589908
499961,SR23-00516874,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Mobile Device,2023-04-05T10:51:08.000,2023-05-13T04:06:57.000,NaN,False,False,3.0,19.0,34.0,10,4,4,41.956416,-87.654253
499964,SR23-00516885,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Mobile Device,2023-04-05T10:52:38.000,2023-05-06T04:14:25.000,NaN,False,False,3.0,19.0,27.0,10,4,4,41.955867,-87.654924
499984,SR23-00516923,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Mobile Device,2023-04-05T10:58:20.000,2023-04-17T11:38:32.000,NaN,False,False,47.0,4.0,23.0,10,4,4,41.726808,-87.598287

In [13]:
bigdf.head()

,sr_number,sr_type,sr_short_code,owner_department,status,origin,created_date,closed_date,zip_code,duplicate,legacy_record,community_area,police_district,police_beat,precinct,created_hour,created_day_of_week,created_month,latitude,longitude
0,SR19-00000014,Tree Removal Request,SEE,Streets and Sanitation,Completed,Phone Call,2019-01-01T00:25:29.000,2019-04-01T08:12:23.000,60643,False,False,53.0,5.0,524.0,40.0,0,3,1,41.673795,-87.653027
1,SR19-00000015,Sidewalk Inspection Request,PBS,CDOT - Department of Transportation,Completed,Internet,2019-01-01T00:26:22.000,2019-10-28T15:15:29.000,60641,False,False,19.0,25.0,2521.0,17.0,0,3,1,41.933926,-87.756002
2,SR19-00000028,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Web,2019-01-01T00:35:57.000,2019-04-15T22:01:28.000,None,False,False,NaN,NaN,NaN,NaN,0,3,1,NaN,NaN
3,SR19-00000029,Abandoned Vehicle Complaint,SKA,Streets and Sanitation,Completed,Web,2019-01-01T00:36:03.000,2019-04-15T22:01:28.000,None,False,False,NaN,NaN,NaN,NaN,0,3,1,NaN,NaN
4,SR19-00000038,Alley Light Out Complaint,SFA,CDOT - Department of Transportation,Completed,Internet,2019-01-01T00:42:25.000,2019-05-17T19:18:57.000,60617,False,False,46.0,4.0,423.0,34.0,0,3,1,41.732152,-87.555196

In [6]:
def getpoint(address):
    loc = geolocator.geocode(address)
    latlong = [loc.latitude, loc.longitude]
    point = Point(latlong[1], latlong[0])   
    return point

In [7]:
def findarea(point):    
    for feature in commarea['features']:
        polygon = shape(feature['geometry'])
        if polygon.contains(point):
           return feature['properties']['area_numbe']
        else:
            continue

In [8]:
def get_commarea(dataframe):
    dataframe['community_area']=''
    i=0
    for row in dataframe.index:
        point = Point(dataframe['location.coordinates'][row][0],dataframe['location.coordinates'][row][1])
        for feature in commarea['features']:
            polygon = shape(feature['geometry'])
            if polygon.contains(point):
                dataframe['community_area'][row] = feature['properties']['area_numbe']
    return dataframe

In [9]:
warming_df = pd.read_csv('../../Warming_Centers_20240116.csv')
cooling_df = pd.read_csv('../../Cooling_Centers_20240116.csv')

In [10]:
warming_df.head()

,SITE TYPE,SITE NAME,HOURS OF OPERATION,ADDRESS,CITY,STATE,ZIP,PHONE,LOCATION
0,Library,Jefferson Park,M and W 10-6; T and Th 12-8; Fri and Sat 9-5; ...,5363 W. Lawrence Ave.,Chicago,IL,60630.0,(312) 744-1998,POINT (-87.761986967 41.967361989)
1,Parks,Taylor Park,M-F 10am-7pm; Sat 10am-2pm; Sun 10am-2pm,47 W. Federal,Chicago,IL,NaN,NaN,POINT (-87.629019975 41.827179981)
2,Library,Uptown,M and W 10-6; T and Th 12-8; Fri and Sat 9-5; ...,929 W. Buena Ave.,Chicago,IL,60613.0,(312) 744-8400,POINT (-87.654211031 41.958200988)
3,Chicago Community College,Daley College,M-F 7am - 8:30 pm; SA-SU CLOSED,7500 S. Pulaski,Chicago,IL,60652.0,773-838-7500,POINT (-87.72377202599995 41.75745600000005)
4,Library,North Pulaski,M and W 10-6; T and Th 12-8; Fri and Sat 9-5; ...,4300 W. North Ave.,Chicago,IL,60639.0,(312) 744-9573,POINT (-87.733982023 41.910143011)

In [ ]:
warming_df = get_commarea(warming_df)